### PR TITLE
Expose onResize hook in gemini-scrollbar

### PR DESCRIPTION
**Pull request by richvdh**
This exposes the `onResize` hook added by https://github.com/noeldelgado/gemini-scrollbar/pull/26.

### CODE REVIEW

**Comment by noeldelgado** [comment]
Thanks for the pull request @richvdh. I am not sure if this approach will work for React components, since we will be creating nodes in `componentDidMount` (the new <object> element) which goes against React rules. We may need to explicitly put the new <object> element in the `render` method and make sure gemini doesn't try to create this element again. 

Will do some tests and see how it goes. For now I updated this package to use gemini `v1.3.x` so the window.resize event is still attached.

**Comment by richvdh** [comment]
In my testing, I found that trying to create the `object` element in `render` gave some very strange results, as I alluded to [here](https://github.com/noeldelgado/gemini-scrollbar/pull/26/files#diff-168726dbe96b3ce427e7fedce31bb0bcR168).

Creating the new element in `componentDidMount` should be fine - once react has created the `GeminiScrollbar`, it doesn't need to look at the children of the DOM element. I wasn't able to find a reference to this being against the rules.

**Comment by richvdh** [comment]
@noeldelgado: any feedback on this?

**Comment by noeldelgado** [comment]
@richvdh: sorry, I haven't had time, I will try to check it this week.

**Comment by noeldelgado** [comment]
Hi @richvdh, I just check it and found out a problem when the `render` method depends on `state` (`setState...`), the result is that React will re-render the whole thing losing the scroll position (scrolling up), I'm thinking about adding an extra `option` to tell `gemini-scrollbar` to do not dynamically add the resizer object (something like `_addResizeObject: <Boolean[true]>`) so React does not render the whole tree on every update, this option is suppose to be used by us specifically (kinda a private option) and not by other users.  I will be working on this in the following days, if you want to see a working example of what I am referring to, let me know, I will try to publish it. Thank you so much for your contribution.

**Comment by richvdh** [comment]
@noeldelgado: I'm not sure I follow you.

It's certainly true that `setState` will make React re-`render` (that's kinda the point). But that shouldn't make the browser lose the scroll position, because the DOM shouldn't change (much). Our application does a `setState` on parent components of the gemini-scrollbar all the time, without problems. Do you have a demonstration of the problem?

**Comment by noeldelgado** [comment]
Hi, @richvdh, 

Sorry for the late response. I just tried this change once again and it works as expected, so I'll proceed to merge it.

Thanks.

**Pull request merged**
