### PR TITLE
Use react-0.14 findDOMNode() API

### PR DESCRIPTION
**Pull request by burmisov**
Not sure how to put it well, so
here is an upgrade to make it work with react@0.14 beta (and the upcoming release, I guess).
It breaks the backwards compatibility, so the major version should be bumped I guess. Or maybe keep it beta for now - so I didn't touch the versioning thing.
Also I commit the dist folder - maybe it's kinda wrong.

### CODE REVIEW

**Comment by sergey-s** [comment]
+1 for 0.14-rc support

**Comment by bruno12mota** [comment]
Only saw this now, pretty much the same #9

**Comment by noeldelgado** [comment]
Released as [v2.0.0](https://github.com/noeldelgado/react-gemini-scrollbar/releases/v2.0.0), thanks!

**Comment by bruno12mota** [comment]
Shouldn't react and react-dom be in the package.json peer dependencies?

**Comment by burmisov** [comment]
@bruno12mota Yeah that's my fault actually. Frankly, I even forgot about the pull-request, and pushed some dep changes to my fork just to my own convenience.
I can do another PR maybe?

**Comment by bruno12mota** [comment]
@burmisov I think so, I actually removed mine as I was using it as a git dependency on my project, I think it's just missing:

```
"peerDependencies" : {
    "react": "^0.14.0",
    "react-dom": "^0.14.0"
}
```

**Pull request merged**
